---
title: "Olivia Handoko MP3"
output: html_document
---
```{r}
library(tidyverse)
library(tsibble)
library(lubridate)
library(fpp3)
library(fpp2)
library(ggfortify)
library(lubridate)
library(shiny)
library(scales)
```

```{r setup, include=FALSE}
read.csv("tree_main_census/data/census-csv-files/scbi.stem3.csv")
read.csv("tree_main_census/data/census-csv-files/scbi.stem2.csv")
read.csv("tree_main_census/data/census-csv-files/scbi.stem1.csv")
```

```{r}
scbi_stem2_notalive <- scbi_stem2 %>%
  filter(DFstatus != "alive" & 
           DFstatus != "prior" & 
           DFstatus != "missing" & 
           DFstatus != "NULL") 

scbi_stem2_alive <- scbi_stem2  %>%
  filter(DFstatus != "stem dead" & 
           DFstatus != "broken below" & 
           DFstatus != "prior" & 
           DFstatus != "missing") 

```


```{r}
scbi_stem1_notalive <- scbi_stem1 %>%
  filter(DFstatus != "alive" & 
           DFstatus != "prior" & 
           DFstatus != "missing" & 
           DFstatus != "NULL") 

scbi_stem1_alive <- scbi_stem1  %>%
  filter(DFstatus != "stem dead" & 
           DFstatus != "broken below" & 
           DFstatus != "prior" & 
           DFstatus != "missing") 

```
______________________________________________________________________________________
```{r}

new_scbi_stem1_notalive <- scbi_stem1_notalive %>% 
    filter(sp %in% c("libe")) 

  
new_scbi_stem1_notalive <-new_scbi_stem1_notalive[duplicated(new_scbi_stem1_notalive$tag), ]
new_scbi_stem1_notalive <-new_scbi_stem1_notalive[duplicated(new_scbi_stem1_notalive$treeID), ]


new_scbi_stem1_alive <-scbi_stem1_alive %>%
  #filter(sp %in% c("libe")) %>%
  filter(quadrat <=300 | 
         quadrat >= 1000) %>%
  filter(treeID <= 300)

new_scbi_stem1_alive <-new_scbi_stem1_alive[duplicated(new_scbi_stem1_alive$tag), ]
new_scbi_stem1_alive <-new_scbi_stem1_alive[duplicated(new_scbi_stem1_alive$treeID), ]


new_scbi_stem2_notalive <- scbi_stem2_notalive %>% 
    filter(sp %in% c("libe")) %>%
    filter(!dbh == 0)


new_scbi_stem2_alive <-scbi_stem2_alive %>%
  #filter(sp %in% c( "libe")) %>%
  filter(quadrat <=300 | 
         quadrat >= 1000) %>%
  filter(treeID <= 300)


new_scbi_stem2_alive <-new_scbi_stem2_alive[duplicated(new_scbi_stem2_alive$tag), ]
new_scbi_stem2_alive <-new_scbi_stem2_alive[duplicated(new_scbi_stem2_alive$treeID), ]


new_scbi_stem3_notalive <- scbi_stem3_notalive %>% 
    filter(sp %in% c("libe")) %>%
  filter(DFstatus != "alive" & 
           DFstatus != "prior" & 
           DFstatus != "missing" & 
           dbh != "NULL") 

new_scbi_stem3_alive <-scbi_stem3_alive %>%
  #filter(sp %in% c( "libe")) %>%
  #filter(StemTag %in% c(1,2)) %>%
  filter(quadrat <=300 |
         quadrat >= 1000) %>%
  filter(treeID <= 300)

```

```{r}
#bind the alive and not alive data together 
total_alive <- rbind(new_scbi_stem1_alive, new_scbi_stem2_alive)  %>% 
  select("sp", "quadrat", "dbh", "ExactDate","date",
         "quadrat", "treeID", "StemTag", "tag",   "MeasureID") %>%
  filter(!dbh %in% c(0, "NULL")) %>%
  filter(StemTag != 10) %>%
  group_by(treeID, StemTag) %>%
  filter(n() >= 2 )
#I want tree ID and StemTag frequency to be more than just one for ST and 3 for treeID

as.data.frame((table(total_alive$treeID))) 
as.data.frame((table(total_alive$StemTag)))

total_alive %>% 
  group_by(treeID, StemTag) %>% 
  summarize(freq = n()) %>%
  filter(freq >= 2)

total_notalive <- rbind(new_scbi_stem2_notalive, 
                        new_scbi_stem1_notalive, new_scbi_stem3_notalive) %>% 
                  select("sp", "dbh", "ExactDate", "quadrat", "date", 
                         "treeID", "StemTag", "tag", "MeasureID") %>%
                  filter(!dbh %in% c(0, "NULL")) 


```

```{r}
total_alive <- total_alive %>%
   mutate(date = mdy(ExactDate))

total_notalive <- total_alive %>%
   mutate(date = mdy(ExactDate))
```

```{r}
new_scbi_stem3_notalive <- new_scbi_stem3_notalive %>%
   mutate(date = mdy(ExactDate))

new_scbi_stem2_notalive <- new_scbi_stem2_notalive %>%
   mutate(date = mdy(ExactDate))

new_scbi_stem1_notalive <- new_scbi_stem1_notalive %>%
   mutate(date = mdy(ExactDate))

```

```{r}
# base_plot <- ggplot(total_alive) + 
#   geom_line(aes(x=date, y=dbh, 
#                 group = interaction(treeID, StemTag), 
#                 color = quadrat))
# base_plot

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "sp", label = "Specie: ",
                choices = c("amar", "beth", "caca", "frni", "havi", "ilve", "libe", "saca", "vipr"),
                selected = "libe"),
                
    ),
  
  mainPanel(
    plotOutput(outputId = "plot")
  )
)
)
#help from  and Sophie's suggestion
server <- function(input, output) {
  
     df_subset <- reactive({
    a <- filter(total_alive, sp == input$sp)
    return(a)
  })
     
      output$plot <- renderPlot({
    ggplot(data = df_subset(), aes_string(x=input$sp, y=input$sp)) +
             geom_line(aes(x=date, y= dbh,
                 group = interaction(treeID, StemTag), 
                 color = quadrat)) +
          ggtitle("Specie's DBH based on Quadrat (2009-2013)") +
          ylab("Diameter At Breast Height") +
          xlab("Year") 
          
                
  })
}

shinyApp(ui = ui, server = server)
```


